# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Grid points for group sequential design numerical integration in C++
#' 
#' @param r Integer, at least 2; default of 18 recommended by Jennison and Turnbull
#' @param mu Mean of normal distribution (scalar) under consideration
#' @param a lower limit of integration (scalar)
#' @param b upper limit of integration (scalar \code{> a})
#' @return A \code{list} with grid points in \code{z} and numerical integration weights in \code{w}
#' @export
gridptsRcpp <- function(r, mu, a, b) {
    .Call(`_gsdmvn_gridptsRcpp`, r, mu, a, b)
}

