#  Copyright (c) 2021 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.
#
#  This file is part of the gsdmvn program.
#
#  gsdmvn is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program. If not, see <http://www.gnu.org/licenses/>.

#' This is the function to generate a R table summarizing the bounds 
#' in the group sequential design generated by 
#' \code{gs_design_ahr} or \code{gs_design_wlr} or \code{gs_design_combo}.
#'
#' @param x an object returned by  \code{gs_design_ahr} or \code{gs_design_wlr} or \code{gs_design_combo} 
#' @param analysis_vars the variables to be put at the summary header of each analysis
#' @param analysis_decimals the displayed number of digits of \code{analysis_vars}
#' @param bound_names names for bounds; default = c("Efficacy", "Futility").
#'
#' @return a data frame summary the bounds of the group sequential design
#' @export
#'
#' @examples
#' # ---------------------------- #
#' #     design parameters        #
#' # ---------------------------- #
#' # enrollment/failure rates
#' enrollRates <- tibble::tibble(Stratum = "All", 
#'                               duration = 12, 
#'                               rate = 1)
#' failRates <- tibble::tibble(Stratum = "All", duration = c(4, 100), 
#'                             failRate = log(2) / 12,
#'                             hr = c(1, .6), 
#'                             dropoutRate = .001)
#' # Information fraction
#' IF <- (1:3)/3 
#' # Analysis times in months; first 2 will be ignored as IF will not be achieved
#' analysisTimes <- c(.01, .02, 36)  
#' # Experimental / Control randomization ratio
#' ratio <- 1 
#' # 1-sided Type I error
#' alpha <- 0.025 
#' # Type II error (1 - power)
#' beta <- .1 
#' # Upper bound
#' upper <- gsdmvn::gs_spending_bound
#' upar <- list(sf = gsDesign::sfLDOF, total_spend = 0.025, param = NULL, timing = NULL)
#' # Lower bound
#' lower <- gsdmvn::gs_spending_bound
#' lpar <- list(sf = gsDesign::sfHSD, total_spend = 0.1, param = 0, timing = NULL)
#' # weight function in WLR
#' wgt00 <- function(x, arm0, arm1){
#'   gsdmvn:::wlr_weight_fh(x, arm0, arm1, rho = 0, gamma = 0)}
#' wgt05 <- function(x, arm0, arm1){
#'   gsdmvn:::wlr_weight_fh(x, arm0, arm1, rho = 0, gamma = .5)}
#' # test in COMBO
#' fh_test <- rbind(
#'   data.frame(rho = 0, gamma = 0, tau = -1, test = 1, Analysis = 1:3,analysisTimes = c(12, 24, 36)), 
#'   data.frame(rho = c(0, 0.5), gamma = 0.5, tau = -1, test = 2:3, Analysis = 3, analysisTimes = 36)
#' )
#' # ---------------------------- #
#' #          ahr                 #
#' # ---------------------------- #
#' x_ahr <- gs_design_ahr2(
#'   enrollRates = enrollRates,
#'   failRates = failRates,
#'   IF = IF, # Information fraction
#'   analysisTimes = analysisTimes, 
#'   ratio = ratio, 
#'   alpha = alpha, 
#'   beta = beta, 
#'   upper = upper,
#'   upar = upar,
#'   lower = lower,
#'   lpar = lpar
#'   )
#' summary_bound(x_ahr)
#' # ---------------------------- #
#' #         wlr                  #
#' # ---------------------------- #
#' x_wlr2 <- gs_design_wlr2(
#'   enrollRates = enrollRates,
#'   failRates = failRates,
#'   weight = wgt05, 
#'   IF = NULL, 
#'   analysisTimes = sort(unique(x_ahr$analysis$Time)), 
#'   ratio = ratio, 
#'   alpha = alpha, 
#'   beta = beta,   
#'   upper = upper,
#'   upar = upar,
#'   lower = lower,
#'   lpar = lpar
#'   )
#' summary_bound(x_wlr)
#' # ---------------------------- #
#' #         max combo            #
#' # ---------------------------- #
#' x_combo <- gsdmvn::gs_design_combo2(
#'   ratio = 1, 
#'   alpha = 0.025, 
#'   beta = 0.2, 
#'   enrollRates = tibble::tibble(Stratum = "All", duration = 12, rate = 500/12),
#'   failRates = tibble::tibble(Stratum = "All", duration = c(4, 100), 
#'                              failRate = log(2) / 15, hr = c(1, .6), dropoutRate = .001), 
#'   fh_test = fh_test,
#'   upper = gsdmvn::gs_spending_combo,
#'   upar = list(sf = gsDesign::sfLDOF, total_spend = 0.025),
#'   lower = gsdmvn::gs_spending_combo,
#'   lpar = list(sf = gsDesign::sfLDOF, total_spend = 0.2))
#' summary_bound(x_combo)
#' 
summary_bound <- function(
  x,
  analysis_vars = NULL,
  analysis_decimals = NULL,
  bound_names = c("Efficacy", "Futility")
){
  
  # get the 
  # (1) bounds table,
  # (2) analysis summary table, 
  # (3) analysis variables to be displayed on the header
  # (4) decimals to be displayed for the analysis variables in (3)
  method <- class(x)[1]
  x_bounds <- x$bounds
  x_analysis <- x$analysis
  K <- max(x_analysis$Analysis)
  if(method == "ahr" || method == "wlr"){
    if(is.null(analysis_vars)){
      analysis_vars <- c("Time", "N", "Events", "AHR", "IF")
    }
    if(is.null(analysis_decimals)){
      analysis_decimals <- c(1, 1, 1, 2, 2)
    }
    temp <- c("Analysis", "Bound", "Nominal p", "~HR at bound", "Alternate hypothesis")
  }
  if(method == "combo"){
    if(is.null(analysis_vars)){
      analysis_vars <- c("Time", "N", "Events")  # TO BE IMPROVED
    }
    if(is.null(analysis_decimals)){
      analysis_decimals <-  c(1, 1, 1)
    }
    temp <- c("Analysis", "Bound", "Nominal p", "Alternate hypothesis")
  }
  
  # set the analysis summary header
  analyses <- x_analysis %>%
    dplyr::group_by(Analysis) %>%
    dplyr::filter(dplyr::row_number() == 1) %>%
    dplyr::select(all_of(c("Analysis", analysis_vars)))
  
  # Merge 3 tables: analyses (one to many), alternate hypothesis table, null hypothesis table
  xy <- full_join(
    # a table under alternative hypothesis
    x_bounds %>% 
      dplyr::filter(hypothesis == "H1") %>% 
      dplyr::rename("Alternate hypothesis" = Probability) %>%
      # change Upper -> bound_names[1], e.g., Efficacy
      # change Lower -> bound_names[2], e.g., Futility
      dplyr::mutate(Bound = dplyr::recode(Bound, "Upper" = bound_names[1], "Lower" = bound_names[2])) %>%
      dplyr::select(all_of(temp)), 
      #select(all_of(c("Analysis", "Bound", "Nominal p", "~HR at bound", "Alternate hypothesis"))),
    
    # a table under null hypothesis
    x_bounds %>% 
      dplyr::filter(hypothesis == "H0") %>%
      dplyr::mutate("Null hypothesis" = Probability,
             Bound = dplyr::recode(Bound, "Upper" = bound_names[1], "Lower" = bound_names[2])) %>%
      dplyr::select(all_of(c("Analysis", "Bound", "Null hypothesis"))),
    
    by = c("Analysis", "Bound"))
  
  # Merge 3 tables: 1 line per analysis, alternate hypothesis table, null hypothesis table
  # if the method is AHR
  if(method == "ahr"){
    # header
    analysis_summary_header <- analyses %>%
      dplyr::select(all_of(c("Analysis", analysis_vars)))
    # bound details
    bound_summary_detail <- xy %>%
      dplyr::select(all_of(c("Analysis", "Bound", "~HR at bound", 
                      "Nominal p", "Alternate hypothesis", "Null hypothesis")))
  }
  
  # if the method is WLR, change AHR to wAHR
  if(method == "wlr"){
    # header
    analysis_summary_header <- analyses %>%
      dplyr::select(all_of(c("Analysis", analysis_vars)))
    if("AHR" %in% analysis_vars){
      analysis_summary_header <- analysis_summary_header %>% dplyr::rename(wAHR = AHR)
    }
    # bound details
    bound_summary_detail <- xy %>%
      dplyr::select(all_of(c("Analysis", "Bound", "~HR at bound", 
                             "Nominal p", "Alternate hypothesis", "Null hypothesis"))) %>% 
      dplyr::rename("~wHR at bound" = "~HR at bound")
  }
  
  # if the method is COMBO, remove the column of "~HR at bound", and remove AHR from header 
  if(method == "combo"){
    # header
    analysis_summary_header <- analyses %>%
      dplyr::select(all_of(c("Analysis", analysis_vars)))
    # bound details
    bound_summary_detail <- xy %>%
      dplyr::select(all_of(c("Analysis", "Bound", #"~HR at bound",
                             "Nominal p", "Alternate hypothesis", "Null hypothesis"))) 
  }
  
  output <- table_ab(
    # A data frame to be show as the summary header
    # It has only ONE record for each value of `byvar`
    table_a = analysis_summary_header,
    # A data frame to be shown as the listing details
    # It has >= 1 records for each value of `byvar`
    table_b = bound_summary_detail,
    decimals = c(0, analysis_decimals),
    byvar = "Analysis")
  
  class(output) <- c(method, class(output))
  return(output)
}