#  Copyright (c) 2021 Merck Sharp & Dohme Corp. a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.
#
#  This file is part of the gsdmvn program.
#
#  gsdmvn is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

summary <- function(x, ...) {
  UseMethod("summary", x)
}

#' summary function to fixed_design class
#' @title summary for \code{fixed_design()} object
#' @param x a fixed design object returned by \code{fixed_design()}
#' @param ... additional arguments
#' @export summary.fixed_design
#' @exportS3Method 
#' @examples
#' fixed_design(x = "AHR", 
#'              alpha = alpha,  
#'              enrollRates = enrollRates, 
#'              failRates = failRates, 
#'              studyDuration = studyDuration, 
#'              ratio = ratio
#'              ) %>% 
#'              summary()
summary.fixed_design <- function(x, ...){
  x_design <- switch(x$design,
                     "AHR" = {"AHR"},
                     "LF" = {"LF"},
                     "RD" = {"RD"},
                     "FH" = {paste0("FH with (rho = ", x$design_par$rho, 
                                    ", gamma = ", gamma = x$design_par$gamma, ")")},
                     "MB" = {paste0("MB with (rho = ", x$design_par$rho, 
                                    ", gamma = ",  x$design_par$gamma, 
                                    ", tau =  ", x$design_par$tau, ")")},  
                     "MaxCombo" = {paste0("MaxCombo with (rho, gamma, tau) = (",
                                          paste(apply(do.call(rbind, x$design_par), 2 , paste , collapse = "," ), collapse = ") and ("),
                                          ")")}
                     )
  
  ans <- x$analysis %>% mutate(Design = x_design)
  class(ans) <- c("fixed_design", x$design, class(ans))
  return(ans)
}


#' This is the function to generate a R table summarizing the bounds 
#' in the group sequential design generated by 
#' \code{gs_design_ahr} or \code{gs_design_wlr} or \code{gs_design_combo}.
#'
#' @param x an object returned by  \code{gs_design_ahr} or \code{gs_design_wlr} or \code{gs_design_combo} 
#' @param analysis_vars the variables to be put at the summary header of each analysis
#' @param analysis_decimals the displayed number of digits of \code{analysis_vars}
#' @param bound_names names for bounds; default = c("Efficacy", "Futility").
#' @export summary.gs_design
#' @exportS3Method
#' @examples
#' # ---------------------------- #
#' #     design parameters        #
#' # ---------------------------- #
#' # enrollment/failure rates
#' enrollRates <- tibble::tibble(Stratum = "All", 
#'                               duration = 12, 
#'                               rate = 1)
#' failRates <- tibble::tibble(Stratum = "All", duration = c(4, 100), 
#'                             failRate = log(2) / 12,
#'                             hr = c(1, .6), 
#'                             dropoutRate = .001)
#' # Information fraction
#' IF <- (1:3)/3 
#' # Analysis times in months; first 2 will be ignored as IF will not be achieved
#' analysisTimes <- c(.01, .02, 36)  
#' # Experimental / Control randomization ratio
#' ratio <- 1 
#' # 1-sided Type I error
#' alpha <- 0.025 
#' # Type II error (1 - power)
#' beta <- .1 
#' # Upper bound
#' upper <- gsdmvn::gs_spending_bound
#' upar <- list(sf = gsDesign::sfLDOF, total_spend = 0.025, param = NULL, timing = NULL)
#' # Lower bound
#' lower <- gsdmvn::gs_spending_bound
#' lpar <- list(sf = gsDesign::sfHSD, total_spend = 0.1, param = 0, timing = NULL)
#' # weight function in WLR
#' wgt00 <- function(x, arm0, arm1){
#'   gsdmvn:::wlr_weight_fh(x, arm0, arm1, rho = 0, gamma = 0)}
#' wgt05 <- function(x, arm0, arm1){
#'   gsdmvn:::wlr_weight_fh(x, arm0, arm1, rho = 0, gamma = .5)}
#' # test in COMBO
#' fh_test <- rbind(
#'   data.frame(rho = 0, gamma = 0, tau = -1, test = 1, Analysis = 1:3,analysisTimes = c(12, 24, 36)), 
#'   data.frame(rho = c(0, 0.5), gamma = 0.5, tau = -1, test = 2:3, Analysis = 3, analysisTimes = 36)
#' )
#' 
#' # ---------------------------- #
#' #          ahr                 #
#' # ---------------------------- #
#' x_ahr <- gs_design_ahr(
#'   enrollRates = enrollRates,
#'   failRates = failRates,
#'   IF = IF, # Information fraction
#'   analysisTimes = analysisTimes, 
#'   ratio = ratio, 
#'   alpha = alpha, 
#'   beta = beta, 
#'   upper = upper,
#'   upar = upar,
#'   lower = lower,
#'   lpar = lpar
#'   )
#' x_ahr %>% summary()
#' x_ahr %>% summary(analysis_vars = c("Time", "Events", "IF"), analysis_decimals = c(1, 0, 2))
#' x_ahr %>% summary(bound_names = c("A is better", "B is better"))
#' 
#' # ---------------------------- #
#' #         wlr                  #
#' # ---------------------------- #
#' x_wlr <- gs_design_wlr(
#'   enrollRates = enrollRates,
#'   failRates = failRates,
#'   weight = wgt05, 
#'   IF = NULL, 
#'   analysisTimes = sort(unique(x_ahr$analysis$Time)), 
#'   ratio = ratio, 
#'   alpha = alpha, 
#'   beta = beta,   
#'   upper = upper,
#'   upar = upar,
#'   lower = lower,
#'   lpar = lpar
#'   )
#' summary(x_wlr)
#' 
#' # ---------------------------- #
#' #         max combo            #
#' # ---------------------------- #
#' x_combo <- gsdmvn::gs_design_combo(
#'   ratio = 1, 
#'   alpha = 0.025, 
#'   beta = 0.2, 
#'   enrollRates = tibble::tibble(Stratum = "All", duration = 12, rate = 500/12),
#'   failRates = tibble::tibble(Stratum = "All", duration = c(4, 100), 
#'                              failRate = log(2) / 15, hr = c(1, .6), dropoutRate = .001), 
#'   fh_test = fh_test,
#'   upper = gsdmvn::gs_spending_combo,
#'   upar = list(sf = gsDesign::sfLDOF, total_spend = 0.025),
#'   lower = gsdmvn::gs_spending_combo,
#'   lpar = list(sf = gsDesign::sfLDOF, total_spend = 0.2))
#' summary(x_combo)
#' 
summary.gs_design <- function(
  x,
  analysis_vars = NULL,
  analysis_decimals = NULL,
  bound_names = c("Efficacy", "Futility")
){
  
  method <- class(x)[class(x) %in% c("ahr", "wlr", "combo")]
  x_bounds <- x$bounds
  x_analysis <- x$analysis
  K <- max(x_analysis$Analysis)
  
  # --------------------------------------------- #
  #     prepare the analysis summary row          #
  # --------------------------------------------- #
  # get the 
  # (1) analysis variables to be displayed on the header
  # (2) decimals to be displayed for the analysis variables in (3)
  if(is.null(analysis_vars) & is.null(analysis_decimals)){
    analysis_vars <- c("Time", "N", "Events", "AHR", ifelse(method == "ahr" || method == "wlr", "IF", "EF"))
    analysis_decimals <- c(1, 1, 1, 2, 2)  
  }else if(is.null(analysis_vars) & !is.null(analysis_decimals)){
    stop("summary: please input analysis_vars and analysis_decimals in pairs!")
  }else if(!is.null(analysis_vars) & is.null(analysis_decimals)){
    stop("summary: please input analysis_vars and analysis_decimals in pairs!")
  }
  # set the analysis summary header
  analyses <- x_analysis %>%
    dplyr::group_by(Analysis) %>%
    dplyr::filter(dplyr::row_number() == 1) %>%
    dplyr::select(all_of(c("Analysis", analysis_vars)))
  
  # --------------------------------------------- #
  #             merge 2 tables:                   #
  #         (1) alternate hypothesis table        #
  #         (2) null hypothesis table             #
  # --------------------------------------------- #
  # table A: a table under alternative hypothesis
  tbl_a <- x_bounds %>% 
    dplyr::filter(hypothesis == "H1") %>% 
    dplyr::rename("Alternate hypothesis" = Probability) %>%
    # change Upper -> bound_names[1], e.g., Efficacy
    # change Lower -> bound_names[2], e.g., Futility
    dplyr::mutate(Bound = dplyr::recode(Bound, "Upper" = bound_names[1], "Lower" = bound_names[2])) 
  
  # table B: a table under null hypothesis  
  tbl_b <- x_bounds %>% 
    dplyr::filter(hypothesis == "H0") %>%
    dplyr::rename("Null hypothesis" = Probability) %>% 
    dplyr::mutate(Bound = dplyr::recode(Bound, "Upper" = bound_names[1], "Lower" = bound_names[2])) %>%
    dplyr::select(all_of(c("Analysis", "Bound", "Null hypothesis")))
  
  xy <- full_join(tbl_a, tbl_b, by = c("Analysis", "Bound"))
  
  # --------------------------------------------- #
  #             merge 2 tables:                   #
  #         (1) analysis summary table            #
  #         (2) xy: bound_summary_detail table    #
  # --------------------------------------------- #
  # Merge 3 tables: 1 line per analysis, alternate hypothesis table, null hypothesis table
  # if the method is AHR
  if(method == "ahr"){
    # header
    analysis_summary_header <- analyses %>% dplyr::select(all_of(c("Analysis", analysis_vars)))
    # bound details
    bound_summary_detail <- xy 
  }
  
  # if the method is WLR, change AHR to wAHR
  if(method == "wlr"){
    # header
    analysis_summary_header <- analyses %>% dplyr::select(all_of(c("Analysis", analysis_vars)))
    if("AHR" %in% analysis_vars){
      analysis_summary_header <- analysis_summary_header %>% dplyr::rename(wAHR = AHR)
    }
    # bound details
    if("~HR at bound" %in% names(xy)){
      bound_summary_detail <- xy %>% dplyr::rename("~wHR at bound" = "~HR at bound")
    }else{
      bound_summary_detail <- xy
    }
  }
  
  # if the method is COMBO, remove the column of "~HR at bound", and remove AHR from header 
  if(method == "combo"){
    # header
    analysis_summary_header <- analyses %>% dplyr::select(all_of(c("Analysis", analysis_vars)))
    # bound details
    if("~HR at bound" %in% names(xy)){
      stop("summary: ~HR at bound can't be display!")
    }else{
      bound_summary_detail <- xy
    }
  }
  
  output <- table_ab(
    # A data frame to be show as the summary header
    # It has only ONE record for each value of `byvar`
    table_a = analysis_summary_header,
    # A data frame to be shown as the listing details
    # It has >= 1 records for each value of `byvar`
    table_b = bound_summary_detail,
    decimals = c(0, analysis_decimals),
    byvar = "Analysis") %>% 
    group_by(Analysis)
  
  if(method == "ahr"){
    output <- output %>% select(Analysis, Bound, Z, `~HR at bound`, `Nominal p`, `Alternate hypothesis`, `Null hypothesis`)
  }else if(method == "wlr"){
    output <- output %>% select(Analysis, Bound, Z, `~wHR at bound`, `Nominal p`, `Alternate hypothesis`, `Null hypothesis`)
  }else if(method == "combo"){
    output <- output %>% select(Analysis, Bound, Z, `Nominal p`, `Alternate hypothesis`, `Null hypothesis`)
  }
  
  class(output) <- c(method, "gs_design", class(output))
  return(output)
}